[workspace]
members = [
    "wp-error",
    "wp-log",
    "wp-specs",
    "wp-conf-base",
    "wp-data-fmt",
]
resolver = "2"

[workspace.package]
# Shared package metadata inherited by members via `*.workspace = true`
version = "{{VERSION}}"
edition = "2024"
license = "Elv2"
authors = ["WarpParse Dev Team"]

[workspace.dependencies]
# Crates shared across members; versions can be centrally managed here.
# Update these as needed.
log = "0.4"
toml = "0.9"
orion-error = "0.5"
orion_conf =  { version = "0.3", features = ["toml"]}
winnow = "~0.7"
derive_more = "2.1"
wp_connector_api = { package = "wp-connector-api",  git = "{{GIT_REPO_SVR}}/wp-open-api", {{GIT_REF}} = "{{OPEN_API_VER}}" }
wp_model_core    = { package = "wp-model-core",     git = "{{GIT_REPO_SVR}}/wp-open-api", {{GIT_REF}} = "{{OPEN_API_VER}}" }

unicode-segmentation = "1.12"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
strum_macros = "0.27"
anyhow = "1.0"
log4rs = { version = "1.4", features = ["gzip"] }
getset = "0.1"
wildmatch = "2.6"
