[package]
name = "wp-specs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
wildmatch = { workspace = true }
