[package]
name = "wp-data-fmt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "wp_data_fmt"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
wp_model_core ={ workspace = true }
